import streamlit as st


def _html(s: str) -> str:
    """Flatten a triple-quoted HTML string to zero indentation per line,
    so Streamlit's markdown parser never mistakes it for a code block."""
    lines = [line.strip() for line in s.strip("\n").splitlines()]
    return "\n".join(lines)


# =========================================================
# QUESTION BANK
# =========================================================

QUESTION_BANK = {

    "Programming": {
        "Easy": [
            {
                "question": "Which of the following is used to store a value in a program?",
                "options": ["Variable", "Loop", "Function", "Compiler"],
                "answer": 0,
                "explanation": "A variable is used to store data or a value that can be used later in a program."
            },
            {
                "question": "Which symbol is commonly used for equality comparison?",
                "options": ["=", "==", "!=", "=>"],
                "answer": 1,
                "explanation": "In many programming languages, == checks whether two values are equal, while = is used for assignment."
            }
        ],
        "Medium": [
            {
                "question": "What is the main purpose of a function?",
                "options": ["To store images", "To repeat or organize reusable logic", "To increase screen brightness", "To create a database"],
                "answer": 1,
                "explanation": "Functions organize reusable pieces of logic, making programs easier to maintain and understand."
            },
            {
                "question": "Which data structure follows the FIFO principle?",
                "options": ["Stack", "Queue", "Tree", "Graph"],
                "answer": 1,
                "explanation": "A queue follows First In, First Out (FIFO). The element inserted first is removed first."
            }
        ],
        "Hard": [
            {
                "question": "What is the average time complexity of binary search?",
                "options": ["O(n)", "O(n²)", "O(log n)", "O(1)"],
                "answer": 2,
                "explanation": "Binary search repeatedly divides the search space in half, giving it an average time complexity of O(log n)."
            }
        ]
    },

    "Computer Science": {
        "Easy": [
            {
                "question": "What does CPU stand for?",
                "options": ["Central Processing Unit", "Computer Processing Utility", "Central Program Utility", "Computer Program Unit"],
                "answer": 0,
                "explanation": "CPU stands for Central Processing Unit. It executes instructions and performs calculations."
            },
            {
                "question": "Which device is primarily used to display output?",
                "options": ["Keyboard", "Mouse", "Monitor", "Scanner"],
                "answer": 2,
                "explanation": "A monitor displays visual output generated by the computer."
            }
        ],
        "Medium": [
            {
                "question": "Which data structure uses the LIFO principle?",
                "options": ["Queue", "Stack", "Array", "Graph"],
                "answer": 1,
                "explanation": "A stack follows Last In, First Out (LIFO). The most recently added item is removed first."
            }
        ],
        "Hard": [
            {
                "question": "Which algorithm is commonly used to find the shortest path in a weighted graph with non-negative edges?",
                "options": ["Bubble Sort", "Dijkstra's Algorithm", "Binary Search", "Depth-First Search"],
                "answer": 1,
                "explanation": "Dijkstra's algorithm finds shortest paths from a source node when edge weights are non-negative."
            }
        ]
    },

    "Artificial Intelligence": {
        "Easy": [
            {
                "question": "What is the main goal of Artificial Intelligence?",
                "options": ["To replace all computers", "To enable machines to perform intelligent tasks", "To increase internet speed", "To store files"],
                "answer": 1,
                "explanation": "AI focuses on creating systems capable of performing tasks that normally require human-like intelligence."
            }
        ],
        "Medium": [
            {
                "question": "What is supervised learning?",
                "options": ["Learning without data", "Learning from labeled data", "Learning only from images", "Learning without an objective"],
                "answer": 1,
                "explanation": "Supervised learning uses labeled training data where the expected output is known."
            }
        ],
        "Hard": [
            {
                "question": "What is overfitting in machine learning?",
                "options": ["When a model performs poorly on training data", "When a model memorizes training data and generalizes poorly", "When a model has no parameters", "When training data is completely removed"],
                "answer": 1,
                "explanation": "Overfitting occurs when a model learns the training data too closely and performs poorly on unseen data."
            }
        ]
    },

    "Database Systems": {
        "Easy": [
            {
                "question": "What does SQL stand for?",
                "options": ["Structured Query Language", "Simple Query Logic", "System Query Language", "Structured Question Language"],
                "answer": 0,
                "explanation": "SQL stands for Structured Query Language and is commonly used to interact with relational databases."
            }
        ],
        "Medium": [
            {
                "question": "Which SQL command is used to retrieve data?",
                "options": ["INSERT", "UPDATE", "SELECT", "DELETE"],
                "answer": 2,
                "explanation": "SELECT is used to retrieve data from one or more tables."
            }
        ],
        "Hard": [
            {
                "question": "What is database normalization mainly used for?",
                "options": ["Increasing duplicate data", "Reducing redundancy and improving data organization", "Deleting all records", "Increasing screen resolution"],
                "answer": 1,
                "explanation": "Normalization organizes database tables to reduce unnecessary redundancy and improve consistency."
            }
        ]
    },

    "Computer Networks": {
        "Easy": [
            {
                "question": "What does IP stand for?",
                "options": ["Internet Protocol", "Internal Program", "Internet Process", "Information Protocol"],
                "answer": 0,
                "explanation": "IP stands for Internet Protocol, which provides addressing and routing for network communication."
            }
        ],
        "Medium": [
            {
                "question": "Which protocol is commonly used to securely access a remote computer?",
                "options": ["HTTP", "FTP", "SSH", "SMTP"],
                "answer": 2,
                "explanation": "SSH provides secure remote access to computers over a network."
            }
        ],
        "Hard": [
            {
                "question": "Which OSI layer is responsible for routing packets between networks?",
                "options": ["Physical Layer", "Data Link Layer", "Network Layer", "Application Layer"],
                "answer": 2,
                "explanation": "The Network Layer handles logical addressing and routing between networks."
            }
        ]
    },

    "Software Engineering": {
        "Easy": [
            {
                "question": "What does SDLC stand for?",
                "options": ["Software Development Life Cycle", "System Data Logic Cycle", "Software Design Level Code", "System Development Logic"],
                "answer": 0,
                "explanation": "SDLC stands for Software Development Life Cycle, which describes the stages involved in developing software."
            }
        ],
        "Medium": [
            {
                "question": "Which activity focuses on understanding what users need from a system?",
                "options": ["Requirements Engineering", "Deployment", "Debugging", "Compilation"],
                "answer": 0,
                "explanation": "Requirements Engineering focuses on identifying, analyzing, documenting, and managing system requirements."
            }
        ],
        "Hard": [
            {
                "question": "What is regression testing?",
                "options": ["Testing only new software", "Testing whether changes have introduced new problems", "Testing hardware components", "Removing old software"],
                "answer": 1,
                "explanation": "Regression testing checks that software changes have not broken previously working functionality."
            }
        ]
    }
}


# =========================================================
# STATE
# =========================================================

def initialize_practice():

    if "practice_subject" not in st.session_state:
        st.session_state.practice_subject = "Programming"
    if "practice_difficulty" not in st.session_state:
        st.session_state.practice_difficulty = "Easy"
    if "practice_question_index" not in st.session_state:
        st.session_state.practice_question_index = 0
    if "practice_score" not in st.session_state:
        st.session_state.practice_score = 0
    if "practice_answered" not in st.session_state:
        st.session_state.practice_answered = False
    if "practice_selected_answer" not in st.session_state:
        st.session_state.practice_selected_answer = None
    if "practice_finished" not in st.session_state:
        st.session_state.practice_finished = False
    if "practice_total_answered" not in st.session_state:
        st.session_state.practice_total_answered = 0


def reset_practice():
    st.session_state.practice_question_index = 0
    st.session_state.practice_score = 0
    st.session_state.practice_answered = False
    st.session_state.practice_selected_answer = None
    st.session_state.practice_finished = False
    st.session_state.practice_total_answered = 0


# =========================================================
# STYLES
# =========================================================

def practice_styles():

    st.markdown(
        """
        <style>

        .practice-header {
            background: linear-gradient(135deg, #0B1F3A 0%, #123B5D 100%);
            padding: 30px 34px;
            border-radius: 20px;
            margin-bottom: 22px;
            color: white;
            box-shadow: 0 8px 25px rgba(11, 31, 58, 0.14);
            position: relative;
            overflow: hidden;
        }

        .practice-header::after {
            content: "";
            position: absolute;
            width: 220px;
            height: 220px;
            background: rgba(98, 214, 200, 0.12);
            border-radius: 50%;
            right: -60px;
            top: -90px;
        }

        .practice-label {
            color: #62D6C8;
            font-size: 12px;
            font-weight: 800;
            letter-spacing: 1.6px;
            margin-bottom: 8px;
            position: relative;
            z-index: 2;
        }

        .practice-header h1 {
            color: white;
            margin: 0;
            font-size: 32px;
            font-weight: 800;
            position: relative;
            z-index: 2;
        }

        .practice-header p {
            color: #C9DCE9;
            margin: 8px 0 0 0;
            font-size: 14px;
            position: relative;
            z-index: 2;
        }

        /* practice-card and start-over card are real st.container(key=...) —
           style them precisely without touching other bordered containers */

        div[class*="st-key-practice_card"],
        div[class*="st-key-restart_card"],
        div[class*="st-key-finish_card"] {
            background: white;
            border: 1px solid #E5EAEE;
            border-radius: 20px;
            padding: 22px 25px;
            box-shadow: 0 6px 22px rgba(11, 31, 58, 0.06);
        }

        div[class*="st-key-restart_card"] {
            border-radius: 18px;
            padding: 19px;
            box-shadow: 0 5px 18px rgba(11, 31, 58, 0.05);
        }

        .card-title {
            color: #0B1F3A;
            font-size: 18px;
            font-weight: 800;
            margin-bottom: 4px;
        }

        .card-subtitle {
            color: #71808C;
            font-size: 13px;
            margin-bottom: 16px;
        }

        .question-number {
            color: #0F766E;
            font-size: 11.5px;
            font-weight: 800;
            letter-spacing: 1px;
            margin-bottom: 9px;
        }

        .question-text {
            color: #20394D;
            font-size: 19px;
            line-height: 1.55;
            font-weight: 700;
            margin: 4px 0 18px 0;
        }

        .progress-wrapper {
            background: #E9F0F2;
            height: 7px;
            border-radius: 20px;
            margin: 0 0 6px 0;
            overflow: hidden;
        }

        .progress-bar {
            height: 7px;
            background: #0F766E;
            border-radius: 20px;
            transition: width 0.3s ease;
        }

        .correct-box {
            background: #EFF9F4;
            border: 1px solid #CBEBDD;
            border-radius: 15px;
            padding: 16px;
            margin-top: 4px;
        }

        .correct-title {
            color: #19734C;
            font-weight: 800;
            font-size: 14px;
        }

        .correct-text {
            color: #496B5B;
            font-size: 12px;
            line-height: 1.5;
            margin-top: 5px;
        }

        .wrong-box {
            background: #FFF4F3;
            border: 1px solid #F0D4D0;
            border-radius: 15px;
            padding: 16px;
            margin-top: 4px;
        }

        .wrong-title {
            color: #B64A40;
            font-weight: 800;
            font-size: 14px;
        }

        .wrong-text {
            color: #765652;
            font-size: 12px;
            line-height: 1.5;
            margin-top: 5px;
        }

        .side-card {
            background: white;
            border: 1px solid #E5EAEE;
            border-radius: 18px;
            padding: 19px;
            margin-bottom: 15px;
            box-shadow: 0 5px 18px rgba(11, 31, 58, 0.05);
        }

        .side-title {
            color: #0B1F3A;
            font-size: 14px;
            font-weight: 800;
            margin-bottom: 12px;
        }

        .stat-row {
            display: flex;
            justify-content: space-between;
            align-items: center;
            padding: 10px 0;
            border-bottom: 1px solid #EDF0F2;
        }

        .stat-row:last-child { border-bottom: none; padding-bottom: 0; }

        .stat-name { color: #71808C; font-size: 12px; }

        .stat-value {
            color: #0F766E;
            font-size: 15px;
            font-weight: 800;
        }

        .finish-card {
            background: linear-gradient(135deg, #EFF9F7, #F7FBFA);
            border: 1px solid #D5EBE7;
            border-radius: 18px;
            padding: 25px;
            text-align: center;
        }

        .finish-icon { font-size: 40px; margin-bottom: 6px; }

        .finish-title {
            color: #0B1F3A;
            font-size: 21px;
            font-weight: 800;
        }

        .finish-score {
            color: #0F766E;
            font-size: 32px;
            font-weight: 800;
            margin: 6px 0;
        }

        .finish-text { color: #687984; font-size: 13px; }

        .stButton > button {
            border-radius: 12px !important;
            min-height: 42px !important;
            border: 1px solid #DCE5E9 !important;
            background: white !important;
            color: #173047 !important;
            font-weight: 700 !important;
            transition: all 0.2s ease !important;
        }

        .stButton > button:hover {
            border-color: #0F766E !important;
            color: #0F766E !important;
        }

        div[data-testid="stButton"] button[kind="primary"] {
            background: #0F766E !important;
            border-color: #0F766E !important;
            color: white !important;
        }

        div[data-testid="stButton"] button[kind="primary"]:hover {
            background: #0D625C !important;
            color: white !important;
        }

        div[role="radiogroup"] {
            gap: 4px !important;
        }

        div[role="radiogroup"] label {
            border: 1px solid #E5EAEE;
            border-radius: 12px;
            padding: 12px 14px !important;
            margin-bottom: 4px;
            transition: all 0.15s ease;
            width: 100%;
        }

        div[role="radiogroup"] label:hover {
            border-color: #62CFC3;
            background: #F7FDFC;
        }

        </style>
        """,
        unsafe_allow_html=True
    )


# =========================================================
# PRACTICE PAGE
# =========================================================

def practice_page():

    initialize_practice()
    practice_styles()

    # =====================================================
    # HEADER
    # =====================================================

    st.markdown(_html("""
        <div class="practice-header">
            <div class="practice-label">✦ BUILD YOUR KNOWLEDGE</div>
            <h1>Practice makes progress. 🎯</h1>
            <p>Test your understanding, learn from mistakes, and strengthen your knowledge.</p>
        </div>
        """), unsafe_allow_html=True)

    # =====================================================
    # FINISHED SCREEN
    # =====================================================

    if st.session_state.practice_finished:

        total_questions = len(
            QUESTION_BANK[st.session_state.practice_subject][st.session_state.practice_difficulty]
        )
        score = st.session_state.practice_score
        percentage = int((score / total_questions) * 100)

        with st.container(key="finish_card"):

            st.markdown(_html(f"""
                <div class="finish-card">
                    <div class="finish-icon">🎉</div>
                    <div class="finish-title">Practice Complete!</div>
                    <div class="finish-score">{score} / {total_questions}</div>
                    <div class="finish-text">You scored {percentage}% on this practice session.</div>
                </div>
                """), unsafe_allow_html=True)

            st.write("")

            col1, col2, col3 = st.columns(3)
            with col1:
                st.metric("Questions", total_questions)
            with col2:
                st.metric("Correct", score)
            with col3:
                st.metric("Accuracy", f"{percentage}%")

            st.write("")

            if st.button("🔄 Practice Again", type="primary", use_container_width=True):
                reset_practice()
                st.rerun()

        return

    # =====================================================
    # MAIN LAYOUT
    # =====================================================

    main_col, side_col = st.columns([2.35, 1], gap="large")

    # =====================================================
    # MAIN PRACTICE
    # =====================================================

    with main_col:

        with st.container(key="practice_card"):

            st.markdown('<div class="card-title">🧠 Practice Session</div>', unsafe_allow_html=True)
            st.markdown(
                '<div class="card-subtitle">Choose your learning area and test yourself.</div>',
                unsafe_allow_html=True
            )

            setting_col1, setting_col2 = st.columns(2)

            with setting_col1:
                subject = st.selectbox("Subject", list(QUESTION_BANK.keys()), key="practice_subject_selector")

            with setting_col2:
                difficulty = st.selectbox("Difficulty", ["Easy", "Medium", "Hard"], key="practice_difficulty_selector")

            if (subject != st.session_state.practice_subject
                    or difficulty != st.session_state.practice_difficulty):
                st.session_state.practice_subject = subject
                st.session_state.practice_difficulty = difficulty
                reset_practice()

            questions = QUESTION_BANK[st.session_state.practice_subject][st.session_state.practice_difficulty]
            question_index = st.session_state.practice_question_index
            total_questions = len(questions)
            current_number = question_index + 1
            progress = question_index / total_questions

            st.markdown(_html(f"""
                <div class="question-number">QUESTION {current_number} OF {total_questions}</div>
                <div class="progress-wrapper">
                    <div class="progress-bar" style="width: {progress * 100}%;"></div>
                </div>
                """), unsafe_allow_html=True)

            current_question = questions[question_index]

            st.markdown(
                _html(f'<div class="question-text">{current_question["question"]}</div>'),
                unsafe_allow_html=True
            )

            selected = st.radio(
                "Choose your answer",
                current_question["options"],
                index=None,
                key=f"answer_{question_index}",
                label_visibility="collapsed"
            )

            # -------------------------------------------------
            # CHECK ANSWER
            # -------------------------------------------------
            if not st.session_state.practice_answered:

                if st.button("✓ Check Answer", type="primary", use_container_width=True):

                    if selected is None:
                        st.warning("Please select an answer first.")
                    else:
                        selected_index = current_question["options"].index(selected)
                        st.session_state.practice_selected_answer = selected_index
                        st.session_state.practice_answered = True
                        st.session_state.practice_total_answered += 1

                        if selected_index == current_question["answer"]:
                            st.session_state.practice_score += 1

                        st.rerun()

            # -------------------------------------------------
            # FEEDBACK
            # -------------------------------------------------
            if st.session_state.practice_answered:

                selected_index = st.session_state.practice_selected_answer
                correct_index = current_question["answer"]

                if selected_index == correct_index:
                    st.markdown(_html(f"""
                        <div class="correct-box">
                            <div class="correct-title">✓ Correct! Great job.</div>
                            <div class="correct-text">{current_question["explanation"]}</div>
                        </div>
                        """), unsafe_allow_html=True)
                else:
                    correct_answer = current_question["options"][correct_index]
                    st.markdown(_html(f"""
                        <div class="wrong-box">
                            <div class="wrong-title">✗ Not quite. Keep learning!</div>
                            <div class="wrong-text">
                                <strong>Correct answer:</strong> {correct_answer}<br><br>
                                {current_question["explanation"]}
                            </div>
                        </div>
                        """), unsafe_allow_html=True)

                st.write("")

                if question_index < total_questions - 1:
                    if st.button("Next Question →", type="primary", use_container_width=True):
                        st.session_state.practice_question_index += 1
                        st.session_state.practice_answered = False
                        st.session_state.practice_selected_answer = None
                        st.rerun()
                else:
                    if st.button("🏆 Finish Practice", type="primary", use_container_width=True):
                        st.session_state.practice_finished = True
                        st.rerun()

    # =====================================================
    # SIDE PANEL
    # =====================================================

    with side_col:

        total_answered = st.session_state.practice_total_answered
        score = st.session_state.practice_score
        accuracy = int((score / total_answered) * 100) if total_answered > 0 else 0

        st.markdown(_html(f"""
            <div class="side-card">
                <div class="side-title">📊 Your session</div>
                <div class="stat-row">
                    <div class="stat-name">Score</div>
                    <div class="stat-value">{score}</div>
                </div>
                <div class="stat-row">
                    <div class="stat-name">Answered</div>
                    <div class="stat-value">{total_answered}</div>
                </div>
                <div class="stat-row">
                    <div class="stat-name">Accuracy</div>
                    <div class="stat-value">{accuracy}%</div>
                </div>
            </div>
            """), unsafe_allow_html=True)

        st.markdown(_html("""
            <div class="side-card">
                <div class="side-title">💡 Practice tips</div>
                <div class="stat-row">
                    <div class="stat-name">Read carefully</div>
                    <div>📖</div>
                </div>
                <div class="stat-row">
                    <div class="stat-name">Think before answering</div>
                    <div>🧠</div>
                </div>
                <div class="stat-row">
                    <div class="stat-name">Learn from mistakes</div>
                    <div>✨</div>
                </div>
                <div class="stat-row">
                    <div class="stat-name">Practice consistently</div>
                    <div>🔥</div>
                </div>
            </div>
            """), unsafe_allow_html=True)

        with st.container(key="restart_card"):
            st.markdown('<div class="side-title">🔄 Start over</div>', unsafe_allow_html=True)
            st.markdown(
                '<div class="card-subtitle">Restart your current practice session whenever you want.</div>',
                unsafe_allow_html=True
            )
            if st.button("Restart Practice", use_container_width=True):
                reset_practice()
                st.rerun()